services:
  pg_pooler:
      container_name: pg_pooler
      image: ghcr.io/postgresml/pgcat:latest
      restart: always
      command: >
        pgcat /etc/pgcat/pgcat.toml
      ports:
        - "6432:6432"
        - "9930:9930"
      depends_on:
        master_psql:
          condition: service_healthy
      volumes:
        - cache:/data
        - ./files/pgcat.toml:/etc/pgcat/pgcat.toml


volumes:
  cache:
    driver: local
